### PR TITLE
Adding HCA Galaxy Instance to list of Analysis Portals

### PR DESCRIPTION
**Pull request by matthewspeir**

### CODE REVIEW

**Comment by matthewspeir** [comment]
Hey @NoopDog. Added you as a reviewer. Feel free to add other reviewers as you see fit.

**Comment by matthewspeir** [comment]
Hey @NoopDog , any comments on the results of the 'Codacy/PR Quality Review'? The failures don't really make sense to me. I followed the format of the other files in the same directory. I'm also not familiar with some of the terms (e.g. 'setext').

Can you provide examples of how I might resolve these issues?

Should I also be adding someone else as a reviewer or assignee?

Thanks!

**Comment by NoopDog** [comment]
Will take a look @matthewspeir

**Comment by MillenniumFalconMechanic** [comment]
Hi @matthewspeir, I reviewed the Codacy failures from your PR and have created a ticket to update the default Codacy settings (#570).

Specifically:
* Front matter should be excluded from certain Codacy checks.
* Header formatting should default to atx, not setext.

**Comment by matthewspeir** [comment]
Thanks! I appreciate it.

**Pull request merged**
