### PR TITLE
Changed the hyperlink in the text.

### PR DESCRIPTION
**Pull request by Aqsa-el**

### CODE REVIEW

**Comment by NoopDog** [comment]
Hi @Aqsa-el can you fix the merge conflicts in this PR, please? Thanks! D

**Comment by Aqsa-el** [comment]
Can you please check if the conflict is resolved now? Thanks
P.S.- If yes, please merge the PR.

**Review by NoopDog — APPROVED** [review]

**Review by NoopDog — APPROVED** [review]

**Comment by NoopDog** [comment]
@Aqsa-el this is live here:
https://data.humancellatlas.org/analyze/portals/polly-by-elucidata

cc: @bvizzier-ucsc

**Comment by Aqsa-el** [comment]
Thanks David.

**Pull request merged**
